import type { ContentItem, Topic } from "./types";

/**
 * Simulated ingestion output from trusted, whitelisted sources
 * (arXiv, GitHub, selected engineering/research blogs).
 * Mix of evergreen/foundational knowledge and recent developments.
 */

export const TOPICS: Topic[] = [
  { id: "llm", label: "LLMs" },
  { id: "rag", label: "RAG & Retrieval" },
  { id: "agents", label: "Agents" },
  { id: "cv", label: "Computer Vision" },
  { id: "rl", label: "Reinforcement Learning" },
  { id: "mlops", label: "MLOps" },
  { id: "nlp", label: "NLP" },
  { id: "diffusion", label: "Diffusion & GenMedia" },
  { id: "fundamentals", label: "ML Fundamentals" },
  { id: "systems", label: "ML Systems & Infra" },
];

export const CATALOG: ContentItem[] = [
  {
    id: "c-attention",
    type: "paper",
    title: "Attention Is All You Need",
    summary: "The transformer paper that replaced recurrence with self-attention.",
    url: "https://arxiv.org/abs/1706.03762",
    source: "arXiv",
    topics: ["llm", "nlp", "fundamentals"],
    level: "intermediate",
    publishedAt: "2017-06-12",
    popularity: 1,
    evergreen: true,
  },
  {
    id: "c-bert",
    type: "paper",
    title: "BERT: Pre-training of Deep Bidirectional Transformers",
    summary: "Masked language modelling that reshaped NLP transfer learning.",
    url: "https://arxiv.org/abs/1810.04805",
    source: "arXiv",
    topics: ["nlp", "llm"],
    level: "intermediate",
    publishedAt: "2018-10-11",
    popularity: 0.93,
    evergreen: true,
  },
  {
    id: "c-illustrated-transformer",
    type: "article",
    title: "The Illustrated Transformer",
    summary: "A visual, step-by-step walkthrough of transformer internals.",
    url: "https://jalammar.github.io/illustrated-transformer/",
    source: "jalammar.github.io",
    topics: ["llm", "fundamentals"],
    level: "beginner",
    publishedAt: "2018-06-27",
    popularity: 0.9,
    evergreen: true,
  },
  {
    id: "c-karpathy-nn",
    type: "repo",
    title: "karpathy/nn-zero-to-hero",
    summary: "Build neural networks and a GPT from scratch, one notebook at a time.",
    url: "https://github.com/karpathy/nn-zero-to-hero",
    source: "GitHub",
    topics: ["fundamentals", "llm"],
    level: "beginner",
    publishedAt: "2022-09-01",
    popularity: 0.88,
    evergreen: true,
  },
  {
    id: "c-nanogpt",
    type: "repo",
    title: "karpathy/nanoGPT",
    summary: "The simplest repo for training medium-sized GPTs, ~300 lines.",
    url: "https://github.com/karpathy/nanoGPT",
    source: "GitHub",
    topics: ["llm", "systems"],
    level: "intermediate",
    publishedAt: "2023-01-11",
    popularity: 0.86,
    evergreen: true,
  },
  {
    id: "c-rag-original",
    type: "paper",
    title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP",
    summary: "The paper that named RAG and paired retrievers with generators.",
    url: "https://arxiv.org/abs/2005.11401",
    source: "arXiv",
    topics: ["rag", "nlp"],
    level: "intermediate",
    publishedAt: "2020-05-22",
    popularity: 0.84,
    evergreen: true,
  },
  {
    id: "c-rag-survey",
    type: "paper",
    title: "A Survey on Retrieval-Augmented Generation",
    summary: "Taxonomy of naive, advanced and modular RAG pipelines.",
    url: "https://arxiv.org/abs/2312.10997",
    source: "arXiv",
    topics: ["rag"],
    level: "intermediate",
    publishedAt: "2023-12-18",
    popularity: 0.72,
    evergreen: false,
  },
  {
    id: "c-llamaindex",
    type: "repo",
    title: "run-llama/llama_index",
    summary: "Data framework for connecting private data to language models.",
    url: "https://github.com/run-llama/llama_index",
    source: "GitHub",
    topics: ["rag", "systems"],
    level: "intermediate",
    publishedAt: "2022-11-02",
    popularity: 0.79,
    evergreen: false,
  },
  {
    id: "c-react-agents",
    type: "paper",
    title: "ReAct: Synergizing Reasoning and Acting in Language Models",
    summary: "Interleaving chain-of-thought with tool use to ground agents.",
    url: "https://arxiv.org/abs/2210.03629",
    source: "arXiv",
    topics: ["agents", "llm"],
    level: "intermediate",
    publishedAt: "2022-10-06",
    popularity: 0.8,
    evergreen: true,
  },
  {
    id: "c-agent-patterns",
    type: "article",
    title: "Building Effective Agents",
    summary: "Why simple, composable patterns beat heavyweight agent frameworks.",
    url: "https://www.anthropic.com/research/building-effective-agents",
    source: "Anthropic Research",
    topics: ["agents"],
    level: "intermediate",
    publishedAt: "2024-12-19",
    popularity: 0.83,
    evergreen: false,
  },
  {
    id: "c-toolformer",
    type: "paper",
    title: "Toolformer: Language Models Can Teach Themselves to Use Tools",
    summary: "Self-supervised API calls learned directly from raw text.",
    url: "https://arxiv.org/abs/2302.04761",
    source: "arXiv",
    topics: ["agents", "llm"],
    level: "advanced",
    publishedAt: "2023-02-09",
    popularity: 0.66,
    evergreen: false,
  },
  {
    id: "c-autogen",
    type: "repo",
    title: "microsoft/autogen",
    summary: "Multi-agent conversation framework for LLM applications.",
    url: "https://github.com/microsoft/autogen",
    source: "GitHub",
    topics: ["agents", "systems"],
    level: "advanced",
    publishedAt: "2023-09-14",
    popularity: 0.7,
    evergreen: false,
  },
  {
    id: "c-resnet",
    type: "paper",
    title: "Deep Residual Learning for Image Recognition",
    summary: "Skip connections that made very deep vision networks trainable.",
    url: "https://arxiv.org/abs/1512.03385",
    source: "arXiv",
    topics: ["cv", "fundamentals"],
    level: "intermediate",
    publishedAt: "2015-12-10",
    popularity: 0.95,
    evergreen: true,
  },
  {
    id: "c-vit",
    type: "paper",
    title: "An Image Is Worth 16x16 Words",
    summary: "Vision Transformers: patches in, convolutions out.",
    url: "https://arxiv.org/abs/2010.11929",
    source: "arXiv",
    topics: ["cv", "llm"],
    level: "advanced",
    publishedAt: "2020-10-22",
    popularity: 0.82,
    evergreen: true,
  },
  {
    id: "c-sam",
    type: "repo",
    title: "facebookresearch/segment-anything",
    summary: "Promptable segmentation model with zero-shot transfer.",
    url: "https://github.com/facebookresearch/segment-anything",
    source: "GitHub",
    topics: ["cv"],
    level: "intermediate",
    publishedAt: "2023-04-05",
    popularity: 0.77,
    evergreen: false,
  },
  {
    id: "c-clip",
    type: "paper",
    title: "Learning Transferable Visual Models From Natural Language",
    summary: "CLIP aligns images and text in one shared embedding space.",
    url: "https://arxiv.org/abs/2103.00020",
    source: "arXiv",
    topics: ["cv", "nlp"],
    level: "advanced",
    publishedAt: "2021-02-26",
    popularity: 0.85,
    evergreen: true,
  },
  {
    id: "c-ddpm",
    type: "paper",
    title: "Denoising Diffusion Probabilistic Models",
    summary: "The noise-then-denoise formulation behind modern image models.",
    url: "https://arxiv.org/abs/2006.11239",
    source: "arXiv",
    topics: ["diffusion", "cv"],
    level: "advanced",
    publishedAt: "2020-06-19",
    popularity: 0.87,
    evergreen: true,
  },
  {
    id: "c-diffusers",
    type: "repo",
    title: "huggingface/diffusers",
    summary: "Pretrained diffusion pipelines for images, audio and video.",
    url: "https://github.com/huggingface/diffusers",
    source: "GitHub",
    topics: ["diffusion", "systems"],
    level: "intermediate",
    publishedAt: "2022-06-01",
    popularity: 0.78,
    evergreen: false,
  },
  {
    id: "c-annotated-diffusion",
    type: "article",
    title: "The Annotated Diffusion Model",
    summary: "Diffusion maths rebuilt line by line in PyTorch.",
    url: "https://huggingface.co/blog/annotated-diffusion",
    source: "Hugging Face Blog",
    topics: ["diffusion", "fundamentals"],
    level: "intermediate",
    publishedAt: "2022-06-07",
    popularity: 0.64,
    evergreen: true,
  },
  {
    id: "c-dqn",
    type: "paper",
    title: "Playing Atari with Deep Reinforcement Learning",
    summary: "Deep Q-networks learning control straight from pixels.",
    url: "https://arxiv.org/abs/1312.5602",
    source: "arXiv",
    topics: ["rl", "fundamentals"],
    level: "intermediate",
    publishedAt: "2013-12-19",
    popularity: 0.81,
    evergreen: true,
  },
  {
    id: "c-ppo",
    type: "paper",
    title: "Proximal Policy Optimization Algorithms",
    summary: "The clipped-objective policy gradient behind RLHF.",
    url: "https://arxiv.org/abs/1707.06347",
    source: "arXiv",
    topics: ["rl", "llm"],
    level: "advanced",
    publishedAt: "2017-07-20",
    popularity: 0.83,
    evergreen: true,
  },
  {
    id: "c-instructgpt",
    type: "paper",
    title: "Training Language Models to Follow Instructions with Human Feedback",
    summary: "How RLHF turned raw language models into assistants.",
    url: "https://arxiv.org/abs/2203.02155",
    source: "arXiv",
    topics: ["llm", "rl"],
    level: "advanced",
    publishedAt: "2022-03-04",
    popularity: 0.88,
    evergreen: true,
  },
  {
    id: "c-dpo",
    type: "paper",
    title: "Direct Preference Optimization",
    summary: "Preference tuning without a separate reward model.",
    url: "https://arxiv.org/abs/2305.18290",
    source: "arXiv",
    topics: ["llm", "rl"],
    level: "advanced",
    publishedAt: "2023-05-29",
    popularity: 0.75,
    evergreen: false,
  },
  {
    id: "c-lora",
    type: "paper",
    title: "LoRA: Low-Rank Adaptation of Large Language Models",
    summary: "Fine-tune huge models by training tiny low-rank adapters.",
    url: "https://arxiv.org/abs/2106.09685",
    source: "arXiv",
    topics: ["llm", "systems"],
    level: "intermediate",
    publishedAt: "2021-06-17",
    popularity: 0.89,
    evergreen: true,
  },
  {
    id: "c-flashattention",
    type: "paper",
    title: "FlashAttention: Fast and Memory-Efficient Exact Attention",
    summary: "IO-aware attention kernels that made long contexts affordable.",
    url: "https://arxiv.org/abs/2205.14135",
    source: "arXiv",
    topics: ["systems", "llm"],
    level: "advanced",
    publishedAt: "2022-05-27",
    popularity: 0.8,
    evergreen: true,
  },
  {
    id: "c-vllm",
    type: "repo",
    title: "vllm-project/vllm",
    summary: "High-throughput LLM serving with paged attention.",
    url: "https://github.com/vllm-project/vllm",
    source: "GitHub",
    topics: ["systems", "mlops"],
    level: "advanced",
    publishedAt: "2023-06-20",
    popularity: 0.79,
    evergreen: false,
  },
  {
    id: "c-ml-debt",
    type: "paper",
    title: "Hidden Technical Debt in Machine Learning Systems",
    summary: "Why the model is the smallest part of a production ML system.",
    url: "https://papers.nips.cc/paper/5656-hidden-technical-debt-in-machine-learning-systems",
    source: "NeurIPS",
    topics: ["mlops", "systems"],
    level: "intermediate",
    publishedAt: "2015-12-07",
    popularity: 0.76,
    evergreen: true,
  },
  {
    id: "c-rules-of-ml",
    type: "article",
    title: "Rules of Machine Learning",
    summary: "Google's field guide to shipping ML that actually works.",
    url: "https://developers.google.com/machine-learning/guides/rules-of-ml",
    source: "Google Developers",
    topics: ["mlops", "fundamentals"],
    level: "beginner",
    publishedAt: "2018-01-15",
    popularity: 0.74,
    evergreen: true,
  },
  {
    id: "c-mlflow",
    type: "repo",
    title: "mlflow/mlflow",
    summary: "Track experiments, package models, manage the ML lifecycle.",
    url: "https://github.com/mlflow/mlflow",
    source: "GitHub",
    topics: ["mlops"],
    level: "beginner",
    publishedAt: "2018-06-05",
    popularity: 0.71,
    evergreen: true,
  },
  {
    id: "c-eval-harness",
    type: "repo",
    title: "EleutherAI/lm-evaluation-harness",
    summary: "Standard harness for benchmarking language model quality.",
    url: "https://github.com/EleutherAI/lm-evaluation-harness",
    source: "GitHub",
    topics: ["mlops", "llm"],
    level: "intermediate",
    publishedAt: "2021-03-10",
    popularity: 0.63,
    evergreen: false,
  },
  {
    id: "c-word2vec",
    type: "paper",
    title: "Efficient Estimation of Word Representations in Vector Space",
    summary: "word2vec: the embedding intuition everything else builds on.",
    url: "https://arxiv.org/abs/1301.3781",
    source: "arXiv",
    topics: ["nlp", "fundamentals"],
    level: "beginner",
    publishedAt: "2013-01-16",
    popularity: 0.86,
    evergreen: true,
  },
  {
    id: "c-scaling-laws",
    type: "paper",
    title: "Scaling Laws for Neural Language Models",
    summary: "Loss as a predictable power law of compute, data and size.",
    url: "https://arxiv.org/abs/2001.08361",
    source: "arXiv",
    topics: ["llm", "fundamentals"],
    level: "advanced",
    publishedAt: "2020-01-23",
    popularity: 0.84,
    evergreen: true,
  },
  {
    id: "c-chinchilla",
    type: "paper",
    title: "Training Compute-Optimal Large Language Models",
    summary: "Chinchilla: most models were badly under-trained on data.",
    url: "https://arxiv.org/abs/2203.15556",
    source: "arXiv",
    topics: ["llm", "systems"],
    level: "advanced",
    publishedAt: "2022-03-29",
    popularity: 0.8,
    evergreen: true,
  },
  {
    id: "c-mixtral",
    type: "paper",
    title: "Mixtral of Experts",
    summary: "Sparse mixture-of-experts routing at open-weight scale.",
    url: "https://arxiv.org/abs/2401.04088",
    source: "arXiv",
    topics: ["llm", "systems"],
    level: "advanced",
    publishedAt: "2024-01-08",
    popularity: 0.69,
    evergreen: false,
  },
  {
    id: "c-transformers-repo",
    type: "repo",
    title: "huggingface/transformers",
    summary: "The default library for pretrained models across modalities.",
    url: "https://github.com/huggingface/transformers",
    source: "GitHub",
    topics: ["llm", "nlp", "systems"],
    level: "beginner",
    publishedAt: "2018-10-29",
    popularity: 0.97,
    evergreen: true,
  },
  {
    id: "c-spinning-up",
    type: "article",
    title: "Spinning Up in Deep RL",
    summary: "OpenAI's from-zero curriculum for reinforcement learning.",
    url: "https://spinningup.openai.com/",
    source: "OpenAI",
    topics: ["rl", "fundamentals"],
    level: "beginner",
    publishedAt: "2018-11-08",
    popularity: 0.72,
    evergreen: true,
  },
  {
    id: "c-distill-momentum",
    type: "article",
    title: "Why Momentum Really Works",
    summary: "An interactive look at the optimizer trick you use every day.",
    url: "https://distill.pub/2017/momentum/",
    source: "Distill",
    topics: ["fundamentals"],
    level: "intermediate",
    publishedAt: "2017-04-04",
    popularity: 0.68,
    evergreen: true,
  },
  {
    id: "c-embeddings-guide",
    type: "article",
    title: "What Are Embeddings?",
    summary: "A practical, math-light tour of vector representations.",
    url: "https://vickiboykis.com/what_are_embeddings/",
    source: "vickiboykis.com",
    topics: ["rag", "nlp", "fundamentals"],
    level: "beginner",
    publishedAt: "2023-06-15",
    popularity: 0.65,
    evergreen: true,
  },
  {
    id: "c-faiss",
    type: "repo",
    title: "facebookresearch/faiss",
    summary: "Battle-tested library for similarity search over dense vectors.",
    url: "https://github.com/facebookresearch/faiss",
    source: "GitHub",
    topics: ["rag", "systems"],
    level: "intermediate",
    publishedAt: "2017-02-22",
    popularity: 0.73,
    evergreen: true,
  },
  {
    id: "c-longcontext",
    type: "paper",
    title: "Lost in the Middle: How Language Models Use Long Contexts",
    summary: "Evidence that models ignore the middle of long prompts.",
    url: "https://arxiv.org/abs/2307.03172",
    source: "arXiv",
    topics: ["llm", "rag"],
    level: "intermediate",
    publishedAt: "2023-07-06",
    popularity: 0.67,
    evergreen: false,
  },
];
